import { useState, useRef, useEffect } from 'react'
import { buildDigestPayload, formatDigestPrompt } from '../domain/digest'
import { detectLLMBackend, callLLM } from '../services/llm'
import type { Category, Session } from '../domain/timer'
import { SettingKey } from '../persistence/storage'
import { loadCredential, saveCredential } from '../services/credentials'
import { useI18n, isI18nKey } from '../i18n'
import type { TKey } from '../i18n'

type Props = {
  categories: Category[]
  sessions: Session[]
  historySessions: Session[]
  today: string
  // optional pre-loaded API key for auto-generation
  claudeApiKey?: string | null
  // ISO week key (e.g. "2026-W12") used for localStorage cache
  weekKey?: string
}

export function DigestView({ categories, sessions, historySessions, today, claudeApiKey, weekKey }: Props) {
  const { t, lang } = useI18n()

  // Resolve cached digest for this week on mount
  const cacheKey = weekKey ? `digest_cache_${weekKey}` : null
  const [digest, setDigest] = useState<string | null>(() => {
    if (!cacheKey) return null
    return localStorage.getItem(cacheKey)
  })
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const lastGeneratedRef = useRef(0)
  const [apiKeyInput, setApiKeyInput] = useState('')
  const [showKeyInput, setShowKeyInput] = useState(false)

  const autoGeneratedRef = useRef(false)
  const [ollamaAvailable, setOllamaAvailable] = useState(false)

  // Detect Ollama on mount
  useEffect(() => {
    fetch('http://localhost:11434/api/tags', { signal: AbortSignal.timeout(500) })
      .then(r => { if (r.ok) setOllamaAvailable(true) })
      .catch(() => {})
  }, [])

  // Auto-generate when AI is available (Ollama or Claude key) and data is ready
  useEffect(() => {
    if ((!claudeApiKey && !ollamaAvailable) || sessions.length === 0 || digest || autoGeneratedRef.current) return
    autoGeneratedRef.current = true
    void handleGenerate(claudeApiKey ?? undefined)
  }, [claudeApiKey, ollamaAvailable, sessions.length, digest]) // eslint-disable-line react-hooks/exhaustive-deps

  async function handleGenerate(overrideKey?: string) {
    const now = Date.now()
    if (now - lastGeneratedRef.current < 10_000) return  // 10-second cooldown
    setError(null)
    const apiKey = overrideKey ?? await loadCredential(SettingKey.AnthropicApiKey)
    const backend = await detectLLMBackend(apiKey)

    if (backend === 'none') {
      setShowKeyInput(true)
      return
    }

    lastGeneratedRef.current = now
    setLoading(true)
    try {
      const payload = buildDigestPayload(categories, sessions, historySessions, today)
      const prompt = formatDigestPrompt(payload, lang)
      const text = await callLLM(prompt, backend, { apiKey: apiKey ?? undefined })
      setDigest(text)
      if (cacheKey) localStorage.setItem(cacheKey, text)
    } catch (e) {
      const msg = e instanceof Error ? e.message : ''
      setError(isI18nKey(msg) ? t(msg as TKey) : t('llm.errorUnknown'))
    } finally {
      setLoading(false)
    }
  }

  async function handleSaveKey() {
    const key = apiKeyInput.trim()
    if (!key) return
    await saveCredential(SettingKey.AnthropicApiKey, key)
    setApiKeyInput('')
    setShowKeyInput(false)
    void handleGenerate(key)
  }

  return (
    <div className="mt-8 rounded-lg border border-white/[0.07] bg-white/[0.02] p-5">
      <div className="mb-3 flex items-center justify-between">
        <h3 className="text-xs font-medium text-zinc-500 uppercase tracking-wider">{t('digest.title')}</h3>
        <button
          onClick={() => handleGenerate()}
          disabled={loading}
          className="rounded-md border border-white/[0.07] bg-white/[0.03] px-3 py-1.5 text-xs text-zinc-400 hover:text-zinc-100 hover:border-white/[0.15] transition-all disabled:opacity-40"
        >
          {loading ? t('digest.generating') : digest ? t('digest.regenerate') : t('digest.generate')}
        </button>
      </div>

      {showKeyInput && (
        <div className="mb-3 flex gap-2">
          <input
            type="password"
            placeholder="sk-ant-… (stored locally)"
            className="flex-1 rounded-lg border border-white/[0.07] bg-white/[0.03] px-3 py-2 text-xs text-zinc-100 placeholder-zinc-600 outline-none focus:border-white/[0.15] transition-all"
            value={apiKeyInput}
            onChange={e => setApiKeyInput(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && handleSaveKey()}
          />
          <button
            onClick={handleSaveKey}
            className="rounded-lg border border-white/[0.07] bg-white/[0.03] px-3 py-2 text-xs text-zinc-400 hover:text-zinc-100 transition-all"
          >
            {t('digest.saveAndGenerate')}
          </button>
        </div>
      )}

      {error && (
        <p className="text-xs text-red-400">{error}</p>
      )}

      {digest ? (
        <p className="text-sm text-zinc-300 leading-relaxed">{digest}</p>
      ) : !loading && !showKeyInput && !error && (
        <p className="text-xs text-zinc-700">{t('digest.hint')}</p>
      )}
    </div>
  )
}
